# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: markhobson/node-chrome

options:
  docker: true
  
pipelines:
  default:
    - step:
        name: run node
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
        artifacts:
          - target/**

  branches:
    # nur der master branch wird gebuilded
    master:
      - step:
          name: Build and Run Docker Image
          script:
           - echo "-----Build Docker Image-----"
           - export IMAGE_LATEST=$REGISTRY_DOMAIN/$REGISTRY_NAME/$APPNAME:latest
           - export REPOSITORY_NAME=$REGISTRY_DOMAIN/$REGISTRY_NAME/$APPNAME
           - export IMAGE_CURRENT=$REPOSITORY_NAME:$BITBUCKET_COMMIT

             # build and push image to docker registry
           - docker login -u $REGISTRY_NAME -p $REGISTRY_PASSWORD $REGISTRY_DOMAIN      
           - docker build -t $IMAGE_CURRENT -t $REPOSITORY_NAME .
           - docker push $IMAGE_CURRENT
           - docker push $IMAGE_LATEST
           - docker run -p 49160:8080 -d $IMAGE_CURRENT
           - docker logout